### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by ralseilii** [TheComputerizer/Specified-Spawning#4] opened 2023-09-28 11:32 UTC
the crash log when using specifiedspawning-1.12.2-0.4.1.1: https://mclo.gs/poyMk6U i just have specifiedspawning,!mixinbooter-8.6 and theimpossiblelibrary-1.12.2-0.3.0 ,i only have these three mods

**Comment by ANightDazingZoroark** [comment] 2023-11-02 04:48
i got the exact same crash report lmao, based on what ive seen there i believe its probably somethin to do w the dependency and not the mod itself

**Comment by TheComputerizer** [comment] 2023-11-02 04:52
The issue is me using a class too early without passing it through the classloader first. It will be fixed soon

**Comment by TheComputerizer** [comment] 2023-11-05 01:08
This should be fixed in 0.4.2

**Closed by TheComputerizer** 2023-11-05 01:08 UTC

**Comment by ralseilii** [comment] 2023-11-05 04:49
will you update forge version of 0.4.2,since only fabric version of it now

**Comment by TheComputerizer** [comment] 2023-11-05 10:01
Oh yeah I accidentally marked it as fabric my bad I fixed it
